apiVersion: v1
kind: Service
metadata:
  name: backend-server
  labels:
    app: backend-server
spec:
  type: NodePort
  selector:
    app: backend-server
  ports:
    - port: 80
      targetPort: 3000
