apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-poc-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: backend-server
  - path: patch-hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: backend-server
  - path: patch-service.yaml
    target:
      kind: Service
      name: backend-server

images:
  - name: aristeukafka/backend-server-k8s-poc
    newTag: dev
